### ISSUE TITLE
r305 timeline master key frames overlay each other

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-bugs#7337]
## Problem description

It is possible to copy master keyframes at the same spot which corrupts timeline and with some additional actions can bring editor to crash or freezing. Before r305 a message saying there's already master keyframe existing have been appearing, but after that build it's possible to duplicate them overlaying each other.

## Attach a .c3p

[r305-timeline-master-keyframe-overlay-each-other.zip](https://github.com/Scirra/Construct-bugs/files/12436405/r305-timeline-master-keyframe-overlay-each-other.zip)

## Steps to reproduce

From c3p:
1. Activate Editing Mode
2. Select three last master kayframes
3. Copy and paste them at one step before

From blank project:
1. Activate Editing Mode
2. Add 3 master keyframes next to each other (from right to left)
3. Copy and paste them at one step before

Result .c3p (I removed non-overlaying keyframes here): 
[corrupted-r305-timeline-master-keyframe-overlay-each-other.zip](https://github.com/Scirra/Construct-bugs/files/12436411/corrupted-r305-timeline-master-keyframe-overlay-each-other.zip)

## Observed result

You will see that two middle keyframes are overlaying each other (Both visually and logically, selecting and moving overlaying one will not move the back one)

![image](https://github.com/Scirra/Construct-bugs/assets/15311427/bf65d322-e223-49bd-af4b-6eca9f617347)

From this, next steps will bring editor to crash:
1. Only leave 1 pair of overlapping master keyframes as others are not contributing here, tho it's not necessary
2. Select corrupted master kayframes and move them anywhere (Make sure to select them all with selection box, as clicking will not select the back one)
3. Undo
4. Redo

Next steps will bring editor to freeze:
1. Activate Editing Mode
2. Select X and Y properties
3. Change Path Mode to Cubic Bezier

## Expected result

Behavior of editor to not allow overlaying keyframes to happen with appropriate pop-up message (from r304):

![image](https://github.com/Scirra/Construct-bugs/assets/15311427/6339ec1d-7226-4256-be6c-51b9567fa5a7)

## More details

**Affected browsers/platforms:** All

**First affected release:** r305

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r355 (beta)
Browser: Chrome 116.0.5845.98
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 456 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
I can't reproduce this in the latest beta. It is likely that it was fixed in the past couple of weeks when sorting out some other problem. Can you confirm this is working as expected in the latest beta?

**NOTE:** Pasting keyframes on top of existing ones, just overwrites the existing keyframes instead of showing a feedback message.

**Comment by elfwy-uwu** [comment]
@DiegoScirra 
I can still reproduce this in the latest beta.
This video shows precisely how to do overlaping keyframes.

https://github.com/Scirra/Construct-bugs/assets/15311427/78e338d3-3ce1-4d7a-8341-c2da36d02305

And this one shows how to crash it. Deleting keyframes is not necesary as i said in the post, just for clarity of the video.

https://github.com/Scirra/Construct-bugs/assets/15311427/7245e4fc-80ac-4465-90e8-1a7891a656d8

Well yeah, i guess the prompt is not needed. It's just the same version the prompt disappeared and the bug was introduced.

**Comment by DiegoScirra** [comment]
I see, I found the problem. This will be fixed in the next beta.
