### ISSUE TITLE
Beta goes to old LTS. Can't open my game in beta release

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#8226]
Normally https://editor.construct.net/beta goes to the most advanced version (I have app installed from this link)

But now its regressed:

![image](https://github.com/user-attachments/assets/c07d6ec9-7d59-4012-88b1-710fa210bf57)

I can't open my game in Beta any more:

![image](https://github.com/user-attachments/assets/8e447dd3-17d6-4741-a945-b1b9efec40b8)

Also set to Beta in the settings:

![image](https://github.com/user-attachments/assets/d487eba3-2641-4c90-ab04-b30863ae5a82)

**Comment by AshleyScirra** [comment]
The redirect is currently wrong - it looks like a problem with the new LTS release system. In the mean time all the beta releases are still there, and you can work around this by loading them directly, e.g. from https://editor.construct.net/r406-2/.

**Comment by AshleyScirra** [comment]
The /beta redirect should be working correctly now.

**Comment by XHXIAIEIN** [comment]
> The /beta redirect should be working correctly now.

it still can't work correctly. /beta will redirect to r397-4
