### ISSUE TITLE
Creating an object with templates don't respect children's layers 

### ISSUE THREAD

**Issue by shotgunanaconda** [Scirra/Construct-bugs#8285]
## Problem description

If i set objects to be a children of an sprite as a template, create the object with hierarchy at a later point, it does not create the children objects at the correct layers. Does not matter if layers are named, unnamed, global or not.

Im using this method to load levels in a large game without having to do have multiple level layouts.

## Attach a .c3p

[bugTemplatesAndLayers.zip](https://github.com/user-attachments/files/17396581/bugTemplatesAndLayers.zip)

## Steps to reproduce

1. run project in debug mode from layout "runThisframe"
2. look at the sprite objects, they should all in the same layer as the template object (layer 2) and not their own (layer 0 and 1)
3.

## Observed result

see above

## Expected result

Create the children in their respective layers

I suggest:
1. if layer name exists: create on layer
2. name doesnt exist: create on master objects layer

This would allow e.g having debug layers for editor while still being useful for larger projects. 

## More details

**Affected browsers/platforms:** Chrome/FF

tried in the latest stable as of 20241016

## System details

</details>

**Comment by DiegoScirra** [comment]
This seems like it makes sense, but in most cases doesn't.

When you use the **Create Object** action, you can specify a layer in which you want the instance to appear in. For single instance creation this is useful as you can put a new instance in any layer, not just the one defined in the editor.

When you bring in hierarchies, the proper thing to do becomes less clear though, because you can specify the layer you want to add the initial instance in, but where should all the children go?

If you place the initial instance in a layer different to the one used in the editor and you then place all the children in the layers they appeared in the editor, the Z ordering will be wrong.

If some layer used in the editor is not present at runtime, the Z ordering will be wrong.

If all the layers exist, but are in a different order, the Z ordering will be wrong.

To get around these problems, all the instances are created in the layer specified in the action and are sorted to look how they looked in the editor, so the hierarchy is visually the same.

Implementing this would only work in the case the root instance is created in the same layer as the editor, all the layers used in the editor exist at runtime and they are also in the same order. All other cases will need to be handled as they are now. On top of that there could be projects out there already relying in the current behaviour, so adding a unique behaviour for a special case could end up creating more problems.

**Comment by shotgunanaconda** [comment]
Thanks for your response, @DiegoScirra. I appreciate the explanation.

I agree with some of your points, but I also have a different perspective on the design. Hierarchy is great for creating modular assets—like in my case, actual levels that can be loaded into a play area. This approach helps avoid using multiple layouts, which has drawbacks. For example, if I need to add a layer or make a similar change, I would have to apply it to each individual layout (global layers would still require it to be added to all layouts). With a large game that currently has over 20 levels, including event triggers, animations, and child objects, splitting it up across multiple layouts just isn't sustainable.

That’s why I was hoping this method could be used. My idea is to create levels in a repository, add them as a hierarchy to a level object, and then load the correct hierarchy in a play layout. Workarounds like this are necessary to maintain a larger game efficiently.

I understand your concerns, and that’s why I think a potential solution could be a check for whether a layer name exists, and if it does, create the child in that layer. While I know nothing is ever as simple as it sounds, it could be an alternative to the current default setup. Perhaps it’s something to consider.

**Comment by Ldwebster111** [comment]
@DiegoScirra I wish this wasn't dismissed as I think it's a valid issue with Construct. Using prefab-style families in separate layout banks is pretty common, and spawning those hierarchies during runtime and needing to sort their objects manually is frustrating in larger projects where a developer is looking to streamline processes.

To get around breaking existing projects, I'd suggest a 'respect layers' checkbox in the create object popup which is off by default. That way we can make use of this option.

**Comment by shotgunanaconda** [comment]
Ah yes the checkbox solution would be great, i forgot to add that to my response.

**Comment by DiegoScirra** [comment]
@AshleyScirra What do you think about this?

I can see how this would be useful and that it is rather cumbersome to do it with events after the creation of a hierarchy, but it's also rather niche and might end up being just another toggle that almost no one will use / know what it does.

**Comment by shotgunanaconda** [comment]
Niche for now but also has great potential :)!

**Comment by Jase0000** [comment]
I do like the sound of this!

I think even if a user has differing layer orders in specific layouts, then I feel this is easy to identify for the user, since they'd question "hey whys the Z order wrong? What to check? Check my hierarchy that I intentionally put on differing layers, all good... Check my layout layers, there's the problem, need to reorder the layers!".

If some layers do not exist, those objects can default to the specified layer in the "create object" action, again, down to the user to identify, where they intentionally designed their hierarchy on differing layers. 

Being a checkbox defaulted to "off" is perfect as this won't break existing projects, including my own! 

If the concern is bloating the "create object" action, perhaps a new action such as "create at layer" or some more cleverly-chosen name. I get that a boolean is probably a immeasurably small check, but of course the create object action is getting beefier over time. What's one more boolean check gonna do!

One other example off top of my head that this could be great for: HUD elements that aren't always spawned in and could be created in at specific times, maybe this HUD element relies on blend modes to get the desired effects, thus requiring 2 or more layers.

**Comment by AshleyScirra** [comment]
I think this should be pursued as a feature request. It's currently working by design and I don't think it's actually that obvious how "preserve hierarchy layers" option should work. For example there are lots of difficulties or edge cases:

- It has to use the layer provided in the "Create object" action - if we change that, it's a breaking change
- If the specified layer is a different one to the layer the root object is placed on:
    - should it ignore the specified layer and put it somewhere else? (this type of thing is a nasty gotcha - cue forum posts saying "why is Construct ignoring the layer parameter?")
    - should it try to create children relative to the new layer?
        - should the relative layers still try to match by name?
            - if layers do not exist by name, what happens? does it just not create those children? (this is another nasty gotcha - cue forum posts saying "why does only part of my hierarchy get created?")
            - this probably means in most cases changing the layer parameter moves part of the hierarchy but not the rest of it, which is also probably a weird result
        - should the relative layers try to match by index offset?
            - might that then accidentally put objects on the wrong layers, e.g. creating parts of hierarchies on the UI layers?
         - what if sub-layers are used and there's a completely different layer tree? does it match same levels of sub-layers? what if some parts of the layer tree are missing?

Overall I think it's another case of a "sounds simple but is actually pretty hard" feature. The current design is straightforward - everything goes on the same layer - and it should be straightforward to get what you want with a series of "move to layer" actions afterwards, so you can work around it like that for the time being. But to get this built-in this would need to be approached as a feature request and all the above problems thought through and solved in the proposal.

**Comment by aabho** [comment]
If I may add:

I think a lot of the edge cases you bring up are solved by the idea of a checkbox or new property for children to have a "preferred layer". You would put in the name of a layer, and the child would be created in that layer (if it exists) regardless of it's default layer in the hierarchy. 

Also, in my opinion:
- It should ignore the layer the parent was created on, and it wouldn't be confusing since "preferred layer" is pretty clear.
- It shouldn't create children relative to the new layer. That's why the dev would define a layer name.
- If layers do not exist by name, it should just ignore the preferred layer setting and be created on the parent layer.
- I don't think it's a "weird result" that changing the parent layer would only move instances without a preferred layer. I imagine scenarios like creating enemies on a different layer, but their shadows would always default to "shadow" layer and their HP bar would always default to "hud", etc.
- There should be no matching based on index offset, this seems more confusing and counter-intuitive.

You're also right that the current design is straightforward, and this is already achievable by moving all objects to layer on creation. It's much more of a convenience feature in my opinion, as I always find that the less "stray" events I have (e.g On created for some random asset), the more organized my workflow is.

**Comment by shotgunanaconda** [comment]
@AshleyScirra @DiegoScirra Thank you both for considering this option,, much appreciated. You're right that it's probably a bit more complicated than it looks on the surface. I agree with the other developers that a checkbox opt-in would solve some of the issues in theory (@aabho described it well). 

I can use events and families to move objects on creation for now, and hopefully you guys can see the potential of enabling this modular approach for upcoming c3 updates.

**Comment by alastair-games** [comment]
Looks like this issue is still not fixed so I added a request here:

https://github.com/Scirra/Construct-feature-requests/issues/710
